drop table yelp_business;
create external table if not exists yelp_business(
attributes_ambience_divey string,
attributes_dietary_restrictions_vegan string,
attributes_happy_hour string,
hours_thursday_open string,
attributes_order_at_counter string,
attributes_hair_types_specialized_in_africanamerican string,
attributes_hair_types_specialized_in_kids string,
attributes_byob string,
hours_friday_open string,
attributes_good_for_latenight string,
attributes_outdoor_seating string,
attributes_alcohol string,
attributes_ambience_classy string,
attributes_by_appointment_only string,
attributes_parking_lot string,
business_id string,
attributes_ambience_touristy string,
attributes_corkage string,
hours_tuesday_open string,
attributes_good_for_brunch string,
categories string,
attributes_waiter_service string,
hours_monday_open string,
name string,
attributes_parking_street string,
attributes_ambience_hipster string,
attributes_byob/corkage string,
attributes_hair_types_specialized_in_straightperms string,
attributes_music_live string,
attributes_dietary_restrictions_dairy-free string,
attributes_music_background_music string,
attributes_price_range string,
attributes_good_for_breakfast string,
attributes_parking_garage string,
attributes_music_karaoke string,
attributes_good_for_dancing string,
review_count string,
attributes_hair_types_specialized_in_asian string,
state string,
attributes_accepts_credit_cards string,
hours_friday_close string,
attributes_good_for_lunch string,
attributes_parking_valet string,
attributes_take-out string,
full_address string,
hours_thursday_close string,
attributes_hair_types_specialized_in_coloring string,
attributes_good_for_dessert string,
attributes_music_video string,
attributes_dietary_restrictions_halal string,
attributes_takes_reservations string,
hours_saturday_open string,
attributes_ages_allowed string,
attributes_ambience_trendy string,
attributes_delivery string,
hours_wednesday_close string,
attributes_wi-fi string,
open string,
city string,
attributes_wheelchair_accessible string,
attributes_dietary_restrictions_gluten-free string,
stars string,
attributes_dietary_restrictions_kosher string,
type string,
attributes_caters string,
attributes_ambience_intimate string,
latitude float,
attributes_good_for_dinner string,
attributes_coat_check string,
longitude float,
hours_monday_close string,
attributes_hair_types_specialized_in_extensions string,
hours_tuesday_close string,
hours_saturday_close string,
attributes_good_for_kids string,
attributes_parking_validated string,
hours_sunday_open string,
attributes_accepts_insurance string,
attributes_music_dj string,
attributes_dietary_restrictions_soy-free string,
attributes_has_tv string,
hours_sunday_close string,
attributes_ambience_casual string,
attributes_hair_types_specialized_in_perms string,
attributes_dogs_allowed string,
attributes_drive-thru string,
attributes_dietary_restrictions_vegetarian string,
hours_wednesday_open string,
attributes_noise_level string,
attributes_smoking string,
attributes_attire string,
attributes_hair_types_specialized_in_curly string,
attributes_good_for_groups string,
neighborhoods string,
attributes_open_24_hours string,
attributes_ambience_romantic string,
attributes_music_jukebox string,
attributes_ambience_upscale string
)
ROW FORMAT SERDE 'org.apache.hadoop.hive.serde2.OpenCSVSerde'
WITH SERDEPROPERTIES (
"separatorChar" = ",",
"quoteChar" = '"',
"escapeChar" = '\\'
)
STORED AS TEXTFILE
LOCATION '/user/w205/yelp/business';

drop table yelp_checkin;
create external table if not exists yelp_checkin(
checkin_info_9-0 int,
checkin_info_9-1 int,
checkin_info_9-2 int,
checkin_info_9-3 int,
checkin_info_9-4 int,
checkin_info_9-5 int,
checkin_info_9-6 int,
checkin_info_20-2 int,
checkin_info_20-3 int,
checkin_info_20-0 int,
checkin_info_20-1 int,
checkin_info_20-6 int,
checkin_info_20-4 int,
checkin_info_20-5 int,
business_id string,
checkin_info_12-1 int,
checkin_info_12-0 int,
checkin_info_12-3 int,
checkin_info_12-2 int,
checkin_info_12-5 int,
checkin_info_12-4 int,
checkin_info_12-6 int,
checkin_info_2-1 int,
checkin_info_15-6 int,
checkin_info_15-4 int,
checkin_info_15-5 int,
checkin_info_15-2 int,
checkin_info_15-3 int,
checkin_info_15-0 int,
checkin_info_15-1 int,
checkin_info_17-1 int,
checkin_info_1-1 int,
checkin_info_22-4 int,
checkin_info_22-5 int,
checkin_info_22-6 int,
checkin_info_22-0 int,
checkin_info_22-1 int,
checkin_info_22-2 int,
checkin_info_22-3 int,
checkin_info_2-0 int,
checkin_info_11-2 int,
checkin_info_11-3 int,
checkin_info_11-0 int,
checkin_info_11-1 int,
checkin_info_11-6 int,
checkin_info_11-4 int,
checkin_info_11-5 int,
checkin_info_16-5 int,
checkin_info_16-4 int,
checkin_info_16-6 int,
checkin_info_16-1 int,
checkin_info_16-0 int,
checkin_info_16-3 int,
checkin_info_16-2 int,
checkin_info_1-0 int,
checkin_info_7-2 int,
checkin_info_1-2 int,
checkin_info_1-3 int,
checkin_info_1-4 int,
checkin_info_1-5 int,
checkin_info_1-6 int,
checkin_info_7-3 int,
checkin_info_7-0 int,
checkin_info_4-1 int,
checkin_info_4-0 int,
checkin_info_4-3 int,
checkin_info_4-2 int,
checkin_info_4-5 int,
checkin_info_4-4 int,
checkin_info_2-5 int,
checkin_info_4-6 int,
checkin_info_2-6 int,
checkin_info_5-2 int,
checkin_info_5-3 int,
checkin_info_19-2 int,
checkin_info_19-3 int,
checkin_info_19-0 int,
checkin_info_19-1 int,
checkin_info_19-6 int,
checkin_info_19-4 int,
checkin_info_19-5 int,
checkin_info_2-3 int,
checkin_info_2-2 int,
checkin_info_6-5 int,
checkin_info_2-4 int,
checkin_info_5-4 int,
checkin_info_5-5 int,
checkin_info_5-6 int,
checkin_info_7-1 int,
checkin_info_7-6 int,
checkin_info_5-1 int,
checkin_info_7-4 int,
checkin_info_7-5 int,
checkin_info_3-2 int,
checkin_info_6-2 int,
checkin_info_21-6 int,
checkin_info_21-5 int,
checkin_info_21-4 int,
checkin_info_21-3 int,
checkin_info_21-2 int,
checkin_info_21-1 int,
checkin_info_21-0 int,
checkin_info_8-5 int,
checkin_info_8-4 int,
checkin_info_8-6 int,
type string,
checkin_info_8-0 int,
checkin_info_8-3 int,
checkin_info_8-2 int,
checkin_info_5-0 int,
checkin_info_17-0 int,
checkin_info_8-1 int,
checkin_info_17-2 int,
checkin_info_17-3 int,
checkin_info_17-4 int,
checkin_info_17-5 int,
checkin_info_17-6 int,
checkin_info_14-3 int,
checkin_info_14-2 int,
checkin_info_14-1 int,
checkin_info_14-0 int,
checkin_info_14-6 int,
checkin_info_14-5 int,
checkin_info_14-4 int,
checkin_info_13-4 int,
checkin_info_13-5 int,
checkin_info_13-6 int,
checkin_info_13-0 int,
checkin_info_13-1 int,
checkin_info_13-2 int,
checkin_info_13-3 int,
checkin_info_10-6 int,
checkin_info_10-5 int,
checkin_info_10-4 int,
checkin_info_10-3 int,
checkin_info_10-2 int,
checkin_info_10-1 int,
checkin_info_10-0 int,
checkin_info_3-5 int,
checkin_info_23-1 int,
checkin_info_23-0 int,
checkin_info_23-3 int,
checkin_info_23-2 int,
checkin_info_23-5 int,
checkin_info_23-4 int,
checkin_info_23-6 int,
checkin_info_3-0 int,
checkin_info_0-5 int,
checkin_info_0-4 int,
checkin_info_0-6 int,
checkin_info_0-1 int,
checkin_info_0-0 int,
checkin_info_0-3 int,
checkin_info_0-2 int,
checkin_info_3-6 int,
checkin_info_6-6 int,
checkin_info_3-4 int,
checkin_info_6-4 int,
checkin_info_6-3 int,
checkin_info_3-3 int,
checkin_info_6-1 int,
checkin_info_6-0 int,
checkin_info_3-1 int,
checkin_info_18-6 int,
checkin_info_18-5 int,
checkin_info_18-4 int,
checkin_info_18-3 int,
checkin_info_18-2 int,
checkin_info_18-1 int,
checkin_info_18-0 int
)
ROW FORMAT SERDE 'org.apache.hadoop.hive.serde2.OpenCSVSerde'
WITH SERDEPROPERTIES (
"separatorChar" = ",",
"quoteChar" = '"',
"escapeChar" = '\\'
)
STORED AS TEXTFILE
LOCATION '/user/w205/yelp/checkin';

drop table yelp_review;
create external table if not exists yelp_review(
user_id string,
review_id string,
text string,
votes_cool int,
business_id string,
votes_funny int,
stars int,
date date,
type string,
votes_useful int
)
ROW FORMAT SERDE 'org.apache.hadoop.hive.serde2.OpenCSVSerde'
WITH SERDEPROPERTIES (
"separatorChar" = ",",
"quoteChar" = '"',
"escapeChar" = '\\'
)
STORED AS TEXTFILE
LOCATION '/user/w205/yelp/review';

drop table yelp_tip;
create external table if not exists yelp_tip(
user_id string,
text string,
business_id string,
likes int,
date date,
type string
)
ROW FORMAT SERDE 'org.apache.hadoop.hive.serde2.OpenCSVSerde'
WITH SERDEPROPERTIES (
"separatorChar" = ",",
"quoteChar" = '"',
"escapeChar" = '\\'
)
STORED AS TEXTFILE
LOCATION '/user/w205/yelp/tip';

drop table yelp_user;
create external table if not exists yelp_user(
yelping_since date,
compliments_plain int,
review_count int,
friends string,
compliments_cute int,
compliments_writer int,
fans int,
compliments_note int,
type string,
compliments_hot int,
compliments_cool int,
compliments_profile int,
average_stars float,
compliments_more int,
elite string,
name string,
user_id string,
votes_cool int,
compliments_list int,
votes_funny int,
compliments_photos int,
compliments_funny int,
votes_useful int
)
ROW FORMAT SERDE 'org.apache.hadoop.hive.serde2.OpenCSVSerde'
WITH SERDEPROPERTIES (
"separatorChar" = ",",
"quoteChar" = '"',
"escapeChar" = '\\'
)
STORED AS TEXTFILE
LOCATION '/user/w205/yelp/user';